struct Cloth
{
    int numVerts;
    int numTris;
    vec3* verts;
    u16* tris;
};

extern Cloth g_cloth0;
extern Cloth g_cloth1;
extern Cloth g_cloth2;
extern Cloth g_cloth3;
extern Cloth g_cloth4;
extern Cloth g_cloth5;
extern Cloth g_cloth6;
extern Cloth g_cloth7;
extern Cloth g_cloth8;
extern Cloth g_cloth9;
extern Cloth g_cloth10;
extern Cloth g_cloth11;
extern Cloth g_cloth12;
extern Cloth g_cloth13;
extern Cloth g_cloth14;
extern Cloth g_cloth15;
extern Cloth g_cloth16;
extern Cloth g_cloth17;
extern Cloth g_cloth18;
extern Cloth g_cloth19;
extern Cloth g_cloth20;
extern Cloth g_cloth21;
extern Cloth g_cloth22;
extern Cloth g_cloth23;
extern Cloth g_cloth24;
extern Cloth g_cloth25;
extern Cloth g_cloth26;
extern Cloth g_cloth27;
extern Cloth g_cloth28;
extern Cloth g_cloth29;
extern Cloth g_cloth30;
extern Cloth g_cloth31;
extern Cloth g_cloth32;
extern Cloth g_cloth33;
extern Cloth g_cloth34;
extern Cloth g_cloth35;
extern Cloth g_cloth36;
extern Cloth g_cloth37;
extern Cloth g_cloth38;
extern Cloth g_cloth39;
extern Cloth g_cloth40;
